package com.arc.frameworkDevice.helper;

import io.appium.java_client.AppiumBy;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.openqa.selenium.By;

public class LocatorGenerator {
    private static Logger log = LogManager.getLogger(LocatorGenerator.class.getName());
    /**
     * Generates a locator from a provided string by replacing a placeholder with a specified value.
     *
     * @param locatorString The string containing the locator with a 'replace' placeholder.
     * @param replacedValue The value to replace the 'replace' placeholder with.
     * @return The generated By locator object.
     */
    public static By generateLocatorFromString(String locatorString, String replacedValue) {
        String locator = locatorString.replaceAll("replace", replacedValue);
        return By.xpath(locator);
    }
    /**
     * Generates a locator for an anchor element with the specified text value.
     *
     * @param textValue The text value of the anchor element.
     * @return The generated By locator object.
     */
    public static By generateLinkLocatorFromText(String textValue) {
        return By.xpath("//a[text()='" + textValue + "']");
    }
    /**
     * Generates a locator for the accessibility id for both Android and iOS.
     *
     * @param locatorValue The value of the accessibility id.
     * @return The generated By locator object.
     */
    public static By generateLocatorAccessibilityId(String locatorValue) {
        return AppiumBy.accessibilityId(locatorValue);
    }
    /**
     * Generates a locator for iOS using NSPredicate format.
     *
     * @param locatorValue The NSPredicate format string.
     * @return The generated By locator object.
     */
    public static By generateLocatoriOSPredicate(String locatorValue) {
        return AppiumBy.iOSNsPredicateString(locatorValue);
    }
    /**
     * Generates a locator for iOS using NSPredicate format with attributes and values.
     *
     * @param attribute The attribute string.
     * @param value     The value string.
     * @return The generated By locator object.
     */
    public static By generateLocatoriOSPredicate(String attribute, String value) {
        String[] key = attribute.split(",");
        String[] attributeValue = value.split(",");
        return AppiumBy.iOSNsPredicateString(getPredicateString(key, attributeValue));
    }
    /**
     * Helper method to generate NSPredicate string based on attribute and value arrays.
     *
     * @param attribute      The array of attribute strings.
     * @param attributeValue The array of attribute value strings.
     * @return The NSPredicate string.
     */
    public static String getPredicateString(String[] attribute, String[] attributeValue) {
        if (attribute.length != attributeValue.length) {
            throw new IllegalArgumentException("Attribute and attributeValue arrays must have the same length");
        }

        StringBuilder queryBuilder = new StringBuilder();

        for (int i = 0; i < attribute.length; i++) {
            if (i > 0) {
                queryBuilder.append(" AND ");
            }

            // If the attribute ends with "CONTAINS", use the "CONTAINS" condition
            if (attribute[i].endsWith("CONTAINS")) {
                queryBuilder.append(attribute[i].replace(" CONTAINS", "")).append(" CONTAINS \"").append(attributeValue[i]).append("\"");
            } else {
                queryBuilder.append(attribute[i]).append(" == \"").append(attributeValue[i]).append("\"");
            }
        }

        return queryBuilder.toString();
    }
    /**
     * Generates a locator for Android using accessibility id format.
     *
     * @param attribute      The attribute string.
     * @param attributeValue The attribute value string.
     * @return The generated By locator object.
     */
    public static By generateLocatorAndroidAccessibilityId(String attribute, String attributeValue) {
        String value = "";
        if(!(attribute.equalsIgnoreCase(""))){
            value = attribute + ", "+ attributeValue;
       }else {
            value=  attributeValue;
       }
        return AppiumBy.accessibilityId(value);
    }

}
